version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(actions)"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: npm
    directory: /mcp
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
    commit-message:
      prefix: "chore(deps-mcp)"
  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development
    commit-message:
      prefix: "chore(deps-cli)"
